### ISSUE TITLE
[BUG] - termscp doesn't use id_rsa default SSH private key to authenticate to SFTP / SCP endpoint

### ISSUE THREAD

**Issue by pcgeek86** [veeso/termscp#126]
## Description

I would like `termscp` to use the `id_rsa` default SSH private key on my local filesystem.

## Steps to reproduce

Try to connect to SFTP or SCP endpoint without using a password. Authentication fails.

## Expected behaviour

By default, `termscp` should use `$HOME/.ssh/id_rsa` to authenticate as `<username>` at `<hostname>`.

## Environment

- OS: [e.g. GNU/Linux Debian 10] MacOS
- Architecture [Arm, x86_64, ...] Intel
- Rust version 
- termscp version 0.9.0
- Protocol used SFTP / SCP
- Remote server version and name

## Log

Report the snippet of the log file containing the unexpected behaviour.
If there is any information you consider to be confidential, shadow it.

**Comment by veeso** [comment]
It should have already been fixed in 0.10. Duplicated of #123

**Comment by pcgeek86** [comment]
Sorry I missed that one.

**Comment by Ragarnoy** [comment]
@veeso it somehow isn´t fixed for me even though i'm on the latest version

```
 2022-11-04T14:43:53.400022129Z [INFO] Client is not connected to remote; connecting to something.something.something.fr:4222
 2022-11-04T14:43:53.473244033Z [ERROR] Authentication failed: [Session(-18)] Authentication failed (username/password)
 2022-11-04T14:43:54.433694461Z [INFO] FileTransferActivity terminated due to 'Authentication'
```

**Comment by namespaceYcZ** [comment]
> It should have already been fixed in 0.10. Duplicated of #123

I don't understand......
I can ssh to an host using my default id_rsa key like this:
![image](https://user-images.githubusercontent.com/3965259/200257947-ed8842ea-60f9-4256-8aef-fae0d794e350.png)
But, it failed on termscp, it said "bad address syntax":
![image](https://user-images.githubusercontent.com/3965259/200259176-17aaae5f-4f61-4f34-9b59-02aa7e36c5e9.png)
(`termscp sftp://test-ubuntu` failed too)
![image](https://user-images.githubusercontent.com/3965259/200258598-fd94d972-5100-447e-bb71-5eac1892cf00.png)
However, I did set the ssh config path:
![image](https://user-images.githubusercontent.com/3965259/200258895-4fff4095-cbf3-4408-bfc3-5d9bb9cb6204.png)

By the way, may I request a new feature, like key remapping? I prefer vim-like keymap.

**Comment by scottbilas** [comment]
I have the same issue, same repro, though a different error message.

My ssh config has more than host info in it - for example `Protocol 2` at the top. This gives an error `IO error (Could not parse configuration file: unknown field: Protocol)`.

Then, if I comment out everything in my config except the Host blocks and retry an scp connection with no user/pass, I get a different error: `authentication failed (could not find any suitable RSA key to authenticate with)`.

(My ssh host does not permit key/pass entry, only ssh, so I'm unable to use termscp to connect because of this problem.)

**Comment by veeso** [comment]
definitely fixed in 0.11

**Comment by namespaceYcZ** [comment]
Did v0.11.0 solve your problem? It does not work for me.

**Comment by veeso** [comment]
Yes, 0.11.0 fixed this. At this point if it still doesn't work for you, please open another issue reporting your ssh configuration and the host parameters.

**Comment by andy65007** [comment]
version 0.19.1 still have this issue. termscp use PEM format ssh key, not OpenSSH format(generate from ssh-keygen by default). could you update termscp for both key format?
